version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  mongodbdata:
  cache:
